steps:
  # 1. Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe maya-backend-repo --location=us-east1; then
          gcloud artifacts repositories create maya-backend-repo --repository-format=docker --location=us-east1 --quiet
        fi

  # 2. Authenticate Docker to Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-east1-docker.pkg.dev

  # 3. Build Docker image (no secrets at build time)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/maya-backend-repo/maya-backend:$SHORT_SHA',
        '.'
      ]

  # 4. Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east1-docker.pkg.dev/$PROJECT_ID/maya-backend-repo/maya-backend:$SHORT_SHA'
      ]

  # 5. Deploy to Cloud Run with runtime secrets injected as env variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'maya-backend-service',
        '--image', 'us-east1-docker.pkg.dev/$PROJECT_ID/maya-backend-repo/maya-backend:$SHORT_SHA',
        '--platform', 'managed',
        '--region', 'us-east1',
        '--allow-unauthenticated',
        '--update-env-vars',
        'AIVEN_DB_PASSWORD=$AIVEN_DB_PASSWORD,OPENAI_API_KEY=$OPENAI_API_KEY,JWT_SECRET=$JWT_SECRET'
      ]

# Define the environment variables that hold your secrets
availableSecrets:
  secretManager:
    - versionName: "projects/PROJECT_NUMBER/secrets/AIVEN_DB_PASSWORD/versions/latest"
      env: "AIVEN_DB_PASSWORD"
    - versionName: "projects/PROJECT_NUMBER/secrets/OPENAI_API_KEY/versions/latest"
      env: "OPENAI_API_KEY"
    - versionName: "projects/PROJECT_NUMBER/secrets/JWT_SECRET/versions/latest"
      env: "JWT_SECRET"

timeout: 900s
