steps:
  # Step 1: Create Artifact Registry repository (if it doesn't exist)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe maya-backend-repo --location=us-central1; then
          gcloud artifacts repositories create maya-backend-repo \
            --repository-format=docker \
            --location=us-central1 \
            --quiet
        fi

  # Step 2: Authenticate Docker to Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/maya-backend-repo/maya-backend:$SHORT_SHA',
        '.'
      ]

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/maya-backend-repo/maya-backend:$SHORT_SHA'
      ]

  # Step 5: Deploy to Cloud Run with runtime secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'maya-backend-service',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/maya-backend-repo/maya-backend:$SHORT_SHA',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--set-secrets',
        'AIVEN_DB_PASSWORD=AIVEN_DB_PASSWORD:latest',
        'OPENAI_API_KEY=OPENAI_API_KEY:latest',
        'JWT_SECRET=JWT_SECRET:latest'
      ]

# Optional build options
options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s
